version: '3.1'
services:
  mysql:
    image: mysql
    container_name: mysql_web
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root #设置root帐号密码
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    entrypoint: bash -c "chown -R mysql:mysql /var/log/mysql && exec /entrypoint.sh mysqld"
    ports:
      - 3306:3306
    volumes:
      - ./data/db:/var/lib/mysql #数据文件挂载
      - ./conf:/etc/mysql #配置文件挂载
      - ./logs:/var/log/mysql #日志文件挂载
